apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tit
roleRef:
  kind: ClusterRole
  name: tit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: default
