apiVersion: apps/v1
kind: Deployment
metadata:
  name: tit-backend
  labels:
    name: tit-backend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: tit-backend
  template:
    metadata:
      labels:
        name: tit-backend
    spec:
      containers:
      - name: tit-backend
        image: {{ .Values.werf.image.api }}
        imagePullPolicy: Always
        env:
        - name: KUBERNETES_USE_IN_CLUSTER_CONFIG
          value: "true"
        - name: DASHBOARD_IMAGE
          value: {{ .Values.werf.image.dashboard }}
        ports:
        - containerPort: 3000
        startupProbe:
          periodSeconds: 5
          httpGet:
            scheme: HTTP
            port: 3000
            path: /
        livenessProbe:
          periodSeconds: 5
          httpGet:
            scheme: HTTP
            port: 3000
            path: /
        envFrom:
        - secretRef:
            name: tit-backend-secret
